---
- include_vars: "{{ ansible_os_family }}.yml"

- name: install sudo
  portage: name=sudo state=present
  when: ansible_os_family == "Gentoo"

- name: install sudo
  apt: name=sudo state=present
  when: ansible_os_family == "Debian"

- name: create wheel group
  group: name=wheel state=present
  tags: vagrant

- name: wheel sudoers
  template: src=wheel-nopasswd dest={{ etc_path }}/etc/sudoers.d/wheel-nopasswd owner=root group=root mode=0440
  when: ansible_os_family != "Solaris"

- name: add {{ name }}
  user: name={{ name }} shell=/bin/bash state=present groups=wheel append=yes
  when: ansible_os_family != "Solaris"

- name: put ssh key for user or for root
  authorized_key: user={{ name if ansible_os_family != "Solaris" else 'root' }} key="{{ ssh_public_key }}"
